### ISSUE TITLE
error when installing via installer

### ISSUE THREAD

**Issue by pdeva** [markosamuli/ansible-linuxbrew#10]
task used:
```
- name: Install linuxbrew
  ansible.builtin.include_role:
    name: "markosamuli.linuxbrew"
  vars:
    linuxbrew_use_installer: true
    ansible_become: true

```

here is the error:

```
TASK [markosamuli.linuxbrew : Download Linuxbrew install script] ***************************************************************************************************************************
fatal: [vagrant]: FAILED! => {"changed": true, "checksum_dest": null, "checksum_src": "ec6cc62725e833ecfffa473a20fcc3e968f38e85", "dest": "/tmp/linuxbrew/install.sh", "elapsed": 0, "msg": "The checksum for /tmp/linuxbrew/install.sh did not match 45c12bcd7765986674142230fc0860f5274903adbe37d582e5537771a1bae0b8; it was bcdaa4ade908e3766c74883f829c3dbb553a9808899bf58702651bd229d0c463.", "src": "/home/vagrant/.ansible/tmp/ansible-tmp-1655076832.0235453-3647468-217907448066365/tmpedxcf781", "url": "https://raw.githubusercontent.com/Homebrew/install/master/install.sh"}
```

**Comment by kai2nenobu** [comment]
I found a workaround. `Role params` can overwrite `linuxbrew_install_url` and `linuxbrew_install_checksum`.  When I specify a  commit of `install.sh` and its checksum in playbook, the role is applied successfully.


```yaml
- hosts: all
  roles:
    - role: markosamuli.linuxbrew
      vars:
        # ↓This is not a role param
        linuxbrew_use_installer: true
      # role params
      linuxbrew_install_url: "https://github.com/Homebrew/install/raw/f1df209948b6e5a561f2d50bafd02fc8c8053607/install.sh"
      linuxbrew_install_checksum: "sha256:3e59181a04200419eb18b714f38cfdea05f496319afc5f17d33059eb7fc9c504"
```

[Document](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html#understanding-variable-precedence) says that `20. role (and include_role) params` takes precedence over `15. role vars (defined in role/vars/main.yml)`
